export const sessions = [
  {
    number: 1,
    ordinal: '1st',
    county: 'Uasin Gishu County',
    region: 'Rift Valley',
    period: '24th–28th September, 2018',
    color: 'from-teal-700 to-teal-900',
    accentColor: 'bg-teal-600',
    status: 'Completed',
    overview: 'The first Senate plenary and committee sittings held away from Nairobi took place in Uasin Gishu County. The sitting created a direct channel for public participation and enabled Senators to inspect national and county government projects in the host region.',
    keyLegislation: [
      'Senate business considered during the first sitting outside Nairobi',
      'Statements and issues raised through public participation',
    ],
    oversight: [
      'Inspection of selected national and county government projects and programmes',
      'Engagement with county leaders and residents on local development priorities',
      'Plenary and committee business conducted in the host county',
    ],
    activities: [
      'Held plenary and committee sittings in Uasin Gishu County from 24th to 28th September 2018.',
      'Provided an opportunity for sectors of society to engage directly with the Senate through public participation.',
      'Inspected projects and programmes implemented by national and county governments.',
      'Strengthened interaction between the Senate, county government, and residents.',
    ],
    impact: 'The first sitting demonstrated how Article 126(1) can bring Senate business closer to counties and communities.',
    participants: 'Senators, county leaders, residents, public institutions, and stakeholders who engaged with the plenary and committee programme.',
    youtubeLink: null,
  },
  {
    number: 2,
    ordinal: '2nd',
    county: 'Kitui County',
    region: 'Eastern Kenya',
    period: '16th–20th September, 2019',
    color: 'from-blue-700 to-blue-900',
    accentColor: 'bg-blue-600',
    status: 'Completed',
    overview: 'The Senate held its plenary and committee sittings in Kitui County after the Senate Business Committee resolved on 28th May 2019 and the House adopted the resolution on 13th June 2019. The planning report documents the logistics, business programme, committee work, public invitations, broadcasting, and county-assembly coordination required to deliver the sitting.',
    keyLegislation: [
      'Bills, papers, statements, and motions considered during three plenary sittings',
      'Public invitations and briefings coordinated by the Senate Business and Committee Sittings Sub-Committee',
    ],
    oversight: [
      'Committee agendas and Order Papers prepared for the Kitui programme',
      'County Assembly chamber and committee rooms prepared for Senate business',
      'Live broadcasting, Hansard, ICT, transport, accommodation, catering, and security coordinated for the sitting',
    ],
    activities: [
      'Held three plenary sittings on 17th, 18th, and 19th September 2019.',
      'Conducted committee sittings with stakeholders and invited members of the public.',
      'Used reconnaissance visits and a leadership courtesy visit to prepare the County Assembly and host county.',
      'Enabled County Assembly members and staff to exchange experience with Senators and Senate staff.',
      'Broadcast plenary and County Public Accounts and Investments Committee proceedings on television, radio, and YouTube.',
      'Included sporting and hosted-dinner side events that supported interaction and capacity building.',
    ],
    impact: 'The report records the sitting as a successful implementation of Article 126 and highlights county-level interaction, public access to proceedings, and institutional capacity building.',
    participants: 'Senators, Senate staff, County Assembly members and staff, county leaders, invited guests, media, and members of the public.',
    successes: [
      "Direct interaction between the Senate and county leaders/citizens strengthened the Senate's profile in representing county interests.",
      'Substantial media coverage before and during the sitting raised public awareness of Senate business.',
      'Addressed pressing local concerns, including 2G network connectivity in Tharaka, Nguuku and Ngomeni wards, the Mung Beans (Ndengu) Bill, land compensation on the Kibwezi–Mutomo–Kitui road, and county health financing.',
      'Senators and County Assembly Members exchanged skills and experience through committee sittings, dinners, and sporting events.',
      "Generated a local economic boost through hotel bookings, restaurants, and transport during the sitting.",
    ],
    challenges: [
      'Inadequate wireless and audio-conferencing systems in some committee rooms.',
      "Poor internet connectivity from the County Assembly's service provider, slowing chamber voting and conferencing functions.",
      'Delays in rigging broadcast equipment and erratic power supply requiring generator backup.',
      'Catering tent too small for the volume of Senators, MCAs, and security personnel, straining food supply.',
      'Late delivery of procurement items, including ICT access points, which derailed installation schedules.',
      'Some Senators did not check into booked hotels without notifying the planning team in advance.',
      'Low turnout by some Senators for scheduled media interviews, straining relationships with broadcasters.',
    ],
    recommendations: [
      'Factor Senate Mashinani sittings into Senate work plans and budgets in advance.',
      'Deploy technical teams for more reconnaissance visits ahead of each sitting.',
      'Invite area Members of the National Assembly to cultivate stronger inter-house relations.',
      'Begin planning for subsequent sittings outside Nairobi earlier in the calendar.',
    ],
    youtubeLink: null,
  },
  {
    number: 3,
    ordinal: '3rd',
    county: 'Turkana County',
    region: 'Northern Kenya',
    period: '25th–29th September, 2023',
    color: 'from-amber-600 to-amber-900',
    accentColor: 'bg-amber-600',
    status: 'Completed',
    overview: 'The Senate resolved on 30th May 2023 to hold plenary and committee sittings in Turkana County. The official report records four plenary sittings and nine committees conducting meetings, site visits, and inspections across Turkana and the surrounding region.',
    keyLegislation: [
      'Papers, statements, motions, and other Senate business considered in four plenary sittings',
      'Committee deliberations on land, energy, security, agriculture, health, education, ICT, and county public accounts',
    ],
    oversight: [
      'Agriculture, Livestock and Fisheries Committee visited Katilu Irrigation Scheme',
      'Energy Committee visited Lake Turkana Wind Power Project and Tullow Oil Company in Lokichar',
      'National Security Committee met the Rural Border Patrol Unit and the Turkana County Assembly committee',
      'County Public Accounts Committee interrogated Turkana County financial statements for FY 2020/2021',
      'Land, Environment and Natural Resources Committee engaged stakeholders on community land challenges',
    ],
    activities: [
      'Held four plenary sittings on 26th, 27th, and 28th September 2023, including morning and afternoon sittings.',
      'Nine Senate committees held meetings and conducted site or inspection visits.',
      'Hosted teachers and students from PAG Secondary School, St. Augustine Boys’ Primary School, KMTC Lodwar Campus, and Turkana University College to observe proceedings.',
      'Facilitated interaction between Senators, Turkana leaders, residents, and the County Assembly.',
      'KEWOSA undertook activities to strengthen links between women Senators and county assemblies.',
      'Used public communications, Senate publications, and displayed historic parliamentary materials to support public awareness.',
    ],
    impact: 'The report records stronger understanding between the Senate, Turkana County Government, and residents, as well as networking and capacity building with the County Assembly.',
    participants: 'Senators, Turkana County Assembly members, county and national officials, residents, students, civil society, and partner institutions.',
    successes: [
      'Direct interaction between the Senate and county leaders/residents enhanced the profile of the Senate in representing and protecting county interests.',
      'Substantial and favourable media coverage before and during the week boosted visibility and public knowledge of Senate work.',
      'Dignitaries and leaders from host and neighbouring counties strengthened diplomatic relations and collaborative legislative initiatives.',
      'Senators and County Assembly Members networked and built capacity through joint committee meetings.',
      'Senate staff exchanged skills with County Assembly staff both formally and through side events such as the dinner hosted by the Clerk of the Senate.',
      'Exemplary security measures and efficient transaction of Senate business, despite a limited staff complement.',
      'Hired Character Generator graphics and high-definition cameras enhanced the broadcast signal and output quality.',
    ],
    challenges: [
      'Limited scheduled flights between Nairobi and Lodwar necessitated road travel for the majority of staff.',
      'Laxity in internet provision by the subcontractor impeded the flow of information and digital communication.',
      "Erratic power supply — Lodwar town is not connected to the national grid — repeatedly disrupted equipment and recording of proceedings.",
      'Delays in procurement and delivery of equipment that needed to be set up and tested in advance.',
    ],
    recommendations: [
      'Provide civic education to host-county residents on the purpose of Senate Mashinani ahead of the sitting to manage expectations.',
      'Reserve appropriate means of transport early to avoid being left with fewer, less desirable options.',
      'Procure portable satellite internet to reduce dependency on fibre-optic connectivity.',
      'Consider Senate pre-qualified contractors for future sittings in the counties.',
      'Identify items for donation to county assemblies during the reconnaissance stage.',
      'Fund CSR activities aligned with each host county\'s areas of interest, including tree-planting initiatives.',
      'Start planning for the next sitting early, with counties invited to express interest in hosting.',
    ],
    expenditure: {
      total: 'KSh 116,246,120',
      note: 'Covered air and ground transport, hotel accommodation, per-diems, audio and ICT equipment, chamber refurbishment, event management (furniture, tents, toilets, air conditioning), outside catering, and live broadcast coverage across KBC, Citizen, KTN, NTV, and local radio.',
    },
    images: [
      { src: '/sessions_images/turkana_assembly_entrance.jpg', caption: 'Main entrance of the County Assembly of Turkana' },
      { src: '/sessions_images/turkana_plenary_chamber.jpg', caption: 'Senate plenary sitting inside the Turkana County Assembly chamber' },
      { src: '/sessions_images/turkana_agriculture_visit.jpg', caption: 'Agriculture, Livestock and Fisheries Committee on a site visit with local farmers' },
      { src: '/sessions_images/turkana_health_visit.jpg', caption: 'Health Committee inspecting a health facility in Turkana County' },
      { src: '/sessions_images/turkana_community_engagement.jpg', caption: 'Senate leadership engaging with the Turkana community' },
    ],
    youtubeLink: null,
  },
  {
    number: 4,
    ordinal: '4th',
    county: 'Busia County',
    region: 'Western Kenya',
    period: '6th–10th October, 2025',
    color: 'from-amber-700 to-amber-900',
    accentColor: 'bg-amber-600',
    status: 'Completed',
    overview: 'The fourth Senate Mashinani sitting in Busia combined four plenary sittings with committee meetings, inspections, a constitutional-amendment town hall, public access to proceedings, and engagement with county and border institutions.',
    keyLegislation: [
      'Constitution of Kenya (Amendment) Bill, 2025 (Senate Bills No. 13 of 2025)',
      'County Governments Additional Allocations (No. 2) Bill (Senate Bills No. 8 of 2025)',
      'Legislative and policy issues raised through committee business and public submissions',
    ],
    oversight: [
      'Agriculture Committee inspected NCPB Malaba Depot and West Kenya Sugar Factory',
      'Education Committee inspected ECDE Centres and Vocational Training Centres',
      'National Cohesion Committee followed up cross-border integration at Malaba One Stop Border Post',
      'Finance and Budget Committee met the Governor on county pending bills',
      'Committees inspected Mulukoba Beach Management Unit and examined fisheries, lake-level, and cross-border challenges',
    ],
    activities: [
      'Held four plenary sittings on 7th, 8th, and 9th October 2025, including morning and afternoon sittings on 8th October.',
      'Held a town hall at Busia Agricultural Training Centre on the Constitution of Kenya (Amendment) Bill, 2025 and received written submissions from the public.',
      'Hosted teachers and students from Alupe University, Busia Township Primary School, and St. Monica Chakol Girls’ High School, alongside Busia County Interfaith Network leaders.',
      'Conducted committee inspections in agriculture, education, cohesion, finance, and fisheries.',
      'Engaged local stakeholders on fisheries management, infrastructure damage, land disputes, and cross-border cooperation.',
    ],
    impact: 'Busia connected plenary business with public submissions, county oversight, fisheries and border concerns, and direct engagement with educational and faith communities.',
    participants: 'Senators, Busia County Assembly members, county leaders, public institutions, traders, fishing communities, students, teachers, faith leaders, and members of the public.',
    successes: [
      "Open plenary sittings, public forums, outreach, and media engagement took Parliamentary proceedings closer to the people and strengthened public appreciation of the Senate's role.",
      'Live media coverage, CSR programmes, and civic education activities increased awareness of the Senate across the county and region.',
      'Dignitaries and leaders from host and neighbouring counties exchanged ideas and strengthened intergovernmental relations.',
      'Committee meetings and public forums let residents, civil society, and youth learn how to submit petitions and memoranda.',
      'Senators and County Assembly Members built capacity through joint committee participation and staff exchanges.',
      "Showcased Busia's strategic role in cross-border trade and drew attention to infrastructure and investment opportunities.",
      'Local vendors, transport providers, and hotels benefited economically from the increased activity during the sitting.',
    ],
    challenges: [
      'Cross-border trade bottlenecks — customs delays, informal trade barriers, and infrastructure limits — require sustained follow-up.',
      'Coordinating multiple levels of government, community groups, and external agencies occasionally caused conflicts and delays.',
      "Public expectations for immediate solutions sometimes exceeded what the Senate's legislative and oversight role could deliver on the spot.",
      'Internet and audiovisual issues affected live streaming and documentation in some instances.',
      'Underbudgeting for some items required emergency purchases during the sitting.',
      'Unclear expectations from the host county over which procured items were for temporary use versus retention.',
    ],
    recommendations: [
      'Provide civic education to host-county residents on the purpose and scope of Senate Mashinani ahead of the sitting.',
      'Procure reliable portable satellite internet to reduce dependency on fibre-optic connectivity.',
      'Agree early and clearly with host counties on which resources are temporary versus retained after the sitting.',
      'Strengthen outreach to local communities, civil society, and businesses to maximise participation.',
      "Fund CSR activities aligned with each host county's areas of interest, including tree-planting initiatives.",
      'Start planning for the next sitting early, with counties invited to express interest in hosting.',
      'Establish monitoring and evaluation mechanisms to capture feedback and track citizen engagement, county partnerships, and legislative effectiveness after each Mashinani.',
    ],
    expenditure: {
      total: 'KSh 81,164,833',
      note: 'Covered air and ground transport, hotel accommodation, per-diems, ICT and connectivity equipment, branded items, chamber refurbishment, donated Speaker\'s seat and Laws of Kenya set, event management, outside catering, and live broadcast coverage by KBC.',
    },
    images: [
      { src: '/sessions_images/busia_assembly_entrance.jpg', caption: 'Main entrance of the County Assembly of Busia' },
      { src: '/sessions_images/busia_plenary_chamber.jpg', caption: 'Senate plenary sitting inside the Busia County Assembly chamber' },
      { src: '/sessions_images/busia_civic_exhibition.jpg', caption: 'Students engage with the Senate civic-awareness exhibition on revenue sharing' },
      { src: '/sessions_images/busia_border_post_visit.jpg', caption: 'Delegation visit to the Busia/Malaba border post area' },
      { src: '/sessions_images/busia_fisheries_visit.jpg', caption: 'Site visit on fisheries and lakeside livelihoods' },
      { src: '/sessions_images/busia_football_match.jpg', caption: 'Football match between the Senate and Busia County Assembly' },
    ],
    youtubeLink: 'https://www.youtube.com/watch?v=VsUV4Hztn58',
  },
  {
    number: 5,
    ordinal: '5th',
    county: 'Kilifi County',
    region: 'Coastal Kenya',
    period: '21st–25th September, 2026',
    color: 'from-blue-700 to-blue-900',
    accentColor: 'bg-blue-600',
    status: 'Planned',
    overview: 'The Kilifi programme is a zero-draft schedule for the fifth sitting of the Senate outside Nairobi. It is not an exit report: the activities below are planned programme items and should not be read as completed outcomes.',
    keyLegislation: [
      'Senate business and committee agendas scheduled for the Kilifi programme',
      'Public participation and delegated-legislation discussions with county institutions',
    ],
    oversight: [
      'Planned inspections of Equalization Fund projects, hospitals, ECDE centres, and county development projects',
      'Planned reviews of fisheries, mining, environment, roads, ICT, energy, water, social protection, and municipal governance',
    ],
    activities: [
      'Planned plenary sittings at the Kilifi County Assembly Chamber on 22nd, 23rd, and 24th September 2026.',
      'Planned oversight of Equalization Fund projects, hospitals, ECDE centres, county headquarters, and the county referral hospital outpatient block.',
      'Planned engagement with fish landing sites, beach management units, traders, women’s groups, and KEMFSED officials on the blue economy.',
      'Planned meetings on coastal mining audits, land petitions, social protection, security, disaster management, ICT, energy, water, and pending bills.',
      'Planned public and institutional engagement through a town hall on inter-community relations and a delegated-legislation experience-sharing meeting.',
    ],
    impact: 'The programme sets out intended oversight, committee, plenary, public-engagement, and staff-exchange activities; outcomes will require a subsequent official report.',
    participants: 'Planned participation by Senators, Kilifi County Assembly and Executive leaders, county committees, national agencies, community groups, and members of the public.',
    // youtubeLink: 'https://www.youtube.com/watch?v=VsUV4Hztn58',
  },
];
